from sqlalchemy import Column, Integer, String, Text
from db import Base


class SubmissionsFlat(Base):
    __tablename__ = "submissions_flat"
    id = Column(Integer, primary_key=True, autoincrement=True)
    filename = Column(Text)
    cik = Column(Text)
    entityType = Column(Text)
    sic = Column(Text)
    sicDescription = Column(Text)
    ownerOrg = Column(Text)
    insiderTransactionForOwnerExists = Column(Integer)
    insiderTransactionForIssuerExists = Column(Integer)
    name = Column(Text)
    tickers = Column(Text)
    exchanges = Column(Text)
    ein = Column(Text)
    lei = Column(Text)
    description = Column(Text)
    website = Column(Text)
    investorWebsite = Column(Text)
    category = Column(Text)
    fiscalYearEnd = Column(Text)
    stateOfIncorporation = Column(Text)
    stateOfIncorporationDescription = Column(Text)
    mailing_street1 = Column(Text)
    mailing_street2 = Column(Text)
    mailing_city = Column(Text)
    mailing_stateOrCountry = Column(Text)
    mailing_zipCode = Column(Text)
    mailing_stateOrCountryDescription = Column(Text)
    mailing_isForeignLocation = Column(Text)
    mailing_foreignStateTerritory = Column(Text)
    mailing_country = Column(Text)
    mailing_countryCode = Column(Text)
    business_street1 = Column(Text)
    business_street2 = Column(Text)
    business_city = Column(Text)
    business_stateOrCountry = Column(Text)
    business_zipCode = Column(Text)
    business_stateOrCountryDescription = Column(Text)
    business_isForeignLocation = Column(Text)
    business_foreignStateTerritory = Column(Text)
    business_country = Column(Text)
    business_countryCode = Column(Text)
    phone = Column(Text)
    flags = Column(Text)
    filings_recent_accessionNumber = Column(Text)
    filings_recent_filingDate = Column(Text)
    filings_recent_reportDate = Column(Text)
    filings_recent_acceptanceDateTime = Column(Text)
    filings_recent_act = Column(Text)
    filings_recent_form = Column(Text)
    filings_recent_fileNumber = Column(Text)
    filings_recent_filmNumber = Column(Text)
    filings_recent_items = Column(Text)
    filings_recent_core_type = Column(Text)
    filings_recent_size = Column(Text)
    filings_recent_isXBRL = Column(Text)
    filings_recent_isInlineXBRL = Column(Text)
    filings_recent_primaryDocument = Column(Text)
    filings_recent_primaryDocDescription = Column(Text)
